Ce notebook englobe une version de Puisssance 4 sous forme de fonction et une version sous forme d'une class.

In [1]:
import pandas as pd
import numpy as np

In [232]:
# initialise la Grille à zerro
def defGrille():
    # liste zero
    listeZero = [0 for i in range(6)]
    #liste name colonnes
    name = ['c'+ str(i+1) for i in range(7)]
    # dictionnaire vide
    dic = {}
    for i in range(7):
        dic[name[i]] = listeZero
    # dictionnaire ==> dataframe
    Grille= pd.DataFrame.from_dict(dic)
    return Grille

#########################################

# obtenir l'index de la position libre dans une colonne en partant de  la fin ===> gravité
def IndexPosition(colonne):
    
    for i in range (len(colonne)):
        index = -i-1
        if colonne[index] == 0 :
            break
    return (len(colonne)+index)


########################################

def placerJeton (user, ChoixColonne, Grille):
    
    colonne = Grille[ChoixColonne].values
    # obtenir l'index de la première position vide en partant du bas == N° ligne
    inx = IndexPosition(colonne)
    if user == 1:
        #Grille[inx][ChoixClonne]=1    # user1
        Grille.loc[inx,ChoixColonne] = 1
    else :
        Grille.loc[inx,ChoixColonne] = 5   # user2
    
    return Grille, inx

#########################################

def verif_colonne(self,ligne, colonne, user):

    result = 0
    gagnant = 0
    limit = ligne + 3
    if limit < Grille.shape[0]:
        result = sum([board[ligne+i,colonne] for i in range(4)])
                
    if result == 4:
        gagnant = 1
    if result == 20:
        gagnant = 2
    
    return gagnant


#######################################0K

def  verif_ligne(ligne, user, grille):
    
    
    gagnant = 0
    # une fenetre de 4 cases qui se déplace 4 fois sur une ligne 
    # desqu'elle trouve une combinaison correspondante , fait un break
    for j in range(4) :
        result = 0
        liste4 = [grille.iloc[ligne][i+j] for i in range(4)]
        result = sum(liste4 )
        if result == 4:
            gagnant = 1
            break
        if result == 20:
            gagnant = 2
            break
            
    return gagnant


            
####################################""OK


def  matrice_diagonale(user, grille):
    
     #colonne : int
    #i = ligne = 2
    #j= colonne = 3
    #j2 = colonne1 = colonne - 3
    # diag1 = [(i,j),(i+1,j+1),(i+2,j+2),(i+3,j+3)]
    # diag2 = [(i,j2),(i+1,j2+1),(i+2,j2+2),(i+3,j2+3)]
    # on commence le calcule de la diagonale à partir de la position (2,3)
    
    
    ligne = 2
    colonne = 3
    colonne1 = colonne - 3
    gagnant = 0
    # une fenetre de 4x4 , on calucle les 2 diagonales
    # des que on trouve, on fait un break
    
    sum_diag1 = 0
    sum_diag2 = 0
    
    for k in range(3):
        # la matrice se déplace sur la verticale  vers la l'haut
        for j in range(4) :
                 # la matrice se déplace sur l'horisontal vers la droite

            sum_diag1 = sum([grille.iloc[ligne+i-k][colonne-i+j] for i in range(4)])
            if (sum_diag1 == 4 or sum_diag2 == 4):
                gagnant = 1
                break

            sum_diag2 = sum([grille.iloc[ligne+i-k][colonne1+i+j] for i in range(4)])
            if (sum_diag1 == 20 or sum_diag2 == 20):
                gagnant = 2
                break


                # test 
           #print ("diag1: " , [(ligne+i-k,colonne-i+j) for i in range(4)])
           #print("diag2 : ",[(ligne+i-k,colonne-3+i+j)for i in range(4)])
            
            
    return gagnant


def verif_all(ligne, ChoixColonne, user, Grille):
    message = ""
    gagnant = 0
    gagnant= verif_ligne(ligne, user, Grille)
    print(1)

    if gagnant == user :
        message = "Ligne"
        print(2)
            
    else:
        gagnant = verif_colonne(ligne,ChoixColonne, user, Grille) 
        print(3)

        if gagnant == user :
            message = "Colonne"
            print(4)
               
        else :

            gagnant = matrice_diagonale(user, Grille)
            print(5)

            if gagnant == user :
                message ="Diagonale"
                print(6)
        
    return gagnant, message


##############################################################
#initialiser la grille    0k
Grille =  defGrille()
print(Grille)
check = 0
print("Veuillez introduire un nombre entre 1 et 7 ou q pour quitter")

for i in range(42):
    
    ######################## User1
    case= input()
    if case == "q":
        break
        
    user = 1
    print(f"Choix joueur {user}")
    ChoixColonne = 'c' + case
    
    if Grille[ChoixColonne][0] != 0:
        print("la colonne est remplie, veuillez choisir une autre colonne")
        case= input("A quelle case voulez-vous jouer ?")
        
        ChoixColonne = 'c'+ case
    
    Grille, ligne = placerJeton (user, ChoixColonne, Grille)
    
    print(Grille)
       
    #check all   
    gagnant, message = verif_all(ligne, ChoixColonne, user, Grille)
    if gagnant == user :
        print(f"BINGO {message}  gagnant  = joueur {user}")  
        break
    
    
    ####################### User2 
    
    user = 2
    print(f"Choix joueur : {user} ")
    case= input()
    ChoixClonne = 'c'+ case
    
    if Grille[ChoixColonne][0] != 0:
        print("la colonne est remplie, veuillez choisir une autre colonne")
        case= input("A quelle case voulez-vous jouer ?")
        
        ChoixColonne = 'c'+ case
        
    Grille, ligne  = placerJeton (user, ChoixClonne, Grille)
    
    print(Grille)
     #check all 
        
   
    gagnant, message = verif_all(ligne, ChoixColonne, user, Grille)
    if gagnant == user :
        print(f"BINGO {message}  gagnant  = joueur {user}")  
        break
    
    
print("Une nouvelle partie!")

   c1  c2  c3  c4  c5  c6  c7
0   0   0   0   0   0   0   0
1   0   0   0   0   0   0   0
2   0   0   0   0   0   0   0
3   0   0   0   0   0   0   0
4   0   0   0   0   0   0   0
5   0   0   0   0   0   0   0
Veuillez introduire un nombre entre 1 et 7 ou q pour quitter
q
Une nouvelle partie!


In [ ]:
class Connect4():
    
    def __init__(self):
        
           self.board = np.zeros((6, 7), dtype=int)
           
   
    # self.board = [[0,0,0,0,0,0,0]
    #               [0,0,0,0,0,0,0]
    #               [0,0,0,0,0,0,0]
    #               [0,0,0,0,0,0,0]
    #               [0,0,0,0,0,0,0]
    #               [0,0,0,0,0,0,0]]
    
    # obtenir l'index de la position libre dans une colonne en partant de  la fin ===> gravité
    
    def displayBoard(self):
        """
        DOCSTRING: Display the board
        """
        board = self.board
        
        return print(board, "\n")

   
 ########################################

    # obtenir l'index de la position libre dans une colonne en partant de  la fin ===> gravité
    def IndexPosition(self,colonne):

        for i in range (len(colonne)):
            index = -i-1
            if colonne[index] == 0 :
                break
        return (len(colonne)+index)


########################################

    def placerJeton (self, user, ChoixColonne):

        colonne = self.board[:,ChoixColonne]
        # obtenir l'index de la première position vide en partant du bas == N° ligne
        ligne= C.IndexPosition(colonne)
        
        if user == 1:
            self.board[ligne,ChoixColonne] = 1  # user1
        else :
            self.board[ligne,ChoixColonne] = 5 # user2

        return ligne
    
#########################################

    def verif_colonne(self,ligne, colonne, user):

        result = 0
        gagnant = 0
        limit = ligne + 3
        if limit < board.shape[0]:
            result = sum([self.board[ligne+i,colonne] for i in range(4)])

        if result == 4:
            gagnant = 1
        if result == 20:
            gagnant = 2

        return gagnant

#########################################

    def  verif_ligne(self, ligne, user, grille):


        gagnant = 0
        # une fenetre de 4 cases qui se déplace 4 fois sur une ligne 
        # desqu'elle trouve une combinaison correspondante , fait un break
        for j in range(4) :
            result = 0
            result = sum([self.board[ligne,i+j] for i in range(4)])

            if result == 4:
                gagnant = 1
                break
            if result == 20:
                gagnant = 2
                break

        return gagnant


            
####################################""OK


    def matrice_diagonale(self, user):

         #colonne : int
        #i = ligne = 2
        #j= colonne = 3
        #j2 = colonne1 = colonne - 3
        # diag1 = [(i,j),(i+1,j+1),(i+2,j+2),(i+3,j+3)]
        # diag2 = [(i,j2),(i+1,j2+1),(i+2,j2+2),(i+3,j2+3)]
        # on commence le calcule de la diagonale à partir de la position (2,3)


        ligne = 2
        colonne = 3
        colonne1 = colonne - 3
        gagnant = 0
        # une fenetre de 4x4 , on calucle les 2 diagonales
        # des que l'on trouve, on fait un break

        sum_diag1 = 0
        sum_diag2 = 0

        for k in range(3):
            # la matrice se déplace sur la verticale  vers la l'haut
            for j in range(4) :
                     # la matrice se déplace sur l'horisontal vers la droite

                sum_diag1 = sum([self.board[ligne+i-k,colonne-i+j] for i in range(4)])
                if (sum_diag1 == 4 or sum_diag2 == 4):
                    gagnant = 1
                    break

                sum_diag2 = sum([self.board[ligne+i-k,colonne1+i+j] for i in range(4)])
                if (sum_diag1 == 20 or sum_diag2 == 20):
                    gagnant = 2
                    break


                    # test 
               #print ("diag1: " , [(ligne+i-k,colonne-i+j) for i in range(4)])
               #print("diag2 : ",[(ligne+i-k,colonne-3+i+j)for i in range(4)])


        return gagnant
    
        
########################################################

   
    def play(self):  #(self, player, choice)
        
        user = 1      
        case= input()
        if case == "q":
            print('\n', "Jeu interrompu par user :", user )
            return self.board, 0, False 
            
               
        print(f"Choix joueur {user}")
        ChoixColonne = int(case)-1
        
        
        if self.board[0,ChoixColonne] != 0:
            print("la colonne est remplie, veuillez choisir une autre colonne")
            case= input("A quelle case voulez-vous jouer ?")
            ChoixColonne = int(case)-1
       
                
        ligne = C.placerJeton (user, ChoixColonne)
        
        
        #C.displayBoard()
        
         # Connect4 test on col
            
        gagnant = C.verif_colonne(ligne, ChoixColonne, user)
        if gagnant == user :
            print(self.board, '\n', "Bingo colonne")
            return self.board, 1, True  
    
        # Connect4 test on line
        gagnant = C.verif_ligne(ligne, ChoixColonne, user)
        if gagnant == user :
            print(self.board,'\n', "Bingo line")
            return self.board, 1, True
        
                       
        # Connect4 test on diag
        gagnant = C.matrice_diagonale(user)
        if gagnant == user :
            print(self.board, '\n', "Bingo diag")
            return self.board, 1, True
            
        #return next_state, reward, terminal
        
         # Move for player2
        
             
        user = 2
        case= input()
        if case == "q":
            print('\n', "Jeu interrompu par user :", user )
            return self.board, 0, False 
        
      
        print(f"Choix joueur {user}")
        ChoixColonne = int(case)-1
        
        
        if self.board[0,ChoixColonne] != 0:
            print("la colonne est remplie, veuillez choisir une autre colonne")
            case= input("A quelle case voulez-vous jouer ?")
            ChoixColonne = int(case)-1
       
                
        ligne = C.placerJeton (user, ChoixColonne)
        
        
        #C.displayBoard()
        
         # Connect4 test on col
        gagnant = C.verif_colonne(ligne, ChoixColonne, user)
        if gagnant == user :
            print(self.board, '\n', "Bingo colonne")
            return self.board, 1, True  
    
        # Connect4 test on line
        gagnant = C.verif_ligne(ligne, ChoixColonne, user)
        if gagnant == user :
            print(self.board,'\n', "Bingo line")
            return self.board, 1, True
        
                       
        # Connect4 test on diag
        gagnant = C.matrice_diagonale(user)
        if gagnant == user :
            print(self.board, '\n', "Bingo diag")
            return self.board, 1, True
        
       

In [308]:
# la premiere versiion


print("Veuillez introduire un nombre entre 1 et 7 ou q pour quitter")

#C =Connect4()
C.displayBoard()

C.play()



Veuillez introduire un nombre entre 1 et 7 ou q pour quitter
[[0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [0 0 5 0 0 0 0]
 [0 0 1 0 0 0 0]
 [1 1 5 5 0 0 0]] 

2
Choix joueur 1
[[0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [0 0 5 0 0 0 0]
 [0 1 1 0 0 0 0]
 [1 1 5 5 0 0 0]] 

4
Choix joueur 2
2
Choix joueur 1
[[0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [0 1 5 0 0 0 0]
 [0 1 1 5 0 0 0]
 [1 1 5 5 0 0 0]] 

2
Choix joueur 2
4
Choix joueur 1
[[0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [0 5 0 0 0 0 0]
 [0 1 5 1 0 0 0]
 [0 1 1 5 0 0 0]
 [1 1 5 5 0 0 0]] 

5
Choix joueur 2
[[0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [0 5 0 0 0 0 0]
 [0 1 5 1 0 0 0]
 [0 1 1 5 0 0 0]
 [1 1 5 5 5 0 0]] 
 Bingo diag
q

 Jeu interrompu par user : 1


In [310]:
print(C.play())

2
Choix joueur 1
[[0 0 0 0 0 0 0]
 [0 1 0 0 0 0 0]
 [0 5 0 0 0 0 0]
 [0 1 5 1 0 0 0]
 [0 1 1 5 0 0 0]
 [1 1 5 5 5 0 0]] 

4
Choix joueur 2
[[0 0 0 0 0 0 0]
 [0 1 0 0 0 0 0]
 [0 5 0 5 0 0 0]
 [0 1 5 1 0 0 0]
 [0 1 1 5 0 0 0]
 [1 1 5 5 5 0 0]] 
 Bingo diag
(array([[0, 0, 0, 0, 0, 0, 0],
       [0, 1, 0, 0, 0, 0, 0],
       [0, 5, 0, 5, 0, 0, 0],
       [0, 1, 5, 1, 0, 0, 0],
       [0, 1, 1, 5, 0, 0, 0],
       [1, 1, 5, 5, 5, 0, 0]]), 1, True)
