POO

### Les classes et le principe d’encapsulation
le principe d'enfermer le code dans une “capsule”, dans un espace en dehors de l’espace global. Cela permet d’éviter d’utiliser des variables globales.

Chaque objet créé à partir d’une classe qui posséde SES attributs de données et SES méthodes qui ne vont pas être accessibles depuis l’extérieur de l’objet et qui ne vont donc pas polluer l’espace global.

Initialiser des objets avec __init__()


Une variable de classe est en fait “partagée” par tous les objets de la classe. On dit que chaque objet de la classe accède à la variable par référence.



In [46]:
class User :
    ancienneté = 0
    
    def __init__(self,age, nom):
        self.user_nom = nom
        self.user_age = age
        
        
    def getName(self):
        print(f"salut je suis {self.user_nom}")
        
pierre = User("Pierre",28)
        
    

In [47]:

print(pierre.ancienneté)
print(pierre.user_age)

0
Pierre


In [48]:
pierre.getName()

salut je suis 28


#### Héritage et polymorphisme en Python orienté objet

En POO, “hériter” signifie “avoir également accès à”. 

Lorsqu’on dit qu’un objet “hérite” des méthodes de la classe qui l’a défini, cela signifie que l’objet peut utiliser ces méthodes; qu’il y a accès.

En python on peut, créer des “sous-classes” ou des classes “enfants” à partir de classes de base ou classes “parentes”.

Ce principe d’héritage permet de créer des classes de base qui vont définir des fonctionnalités communes à plusieurs classes puis des sous-classes qui vont hériter de ces fonctionnalités et pouvoir également définir leurs propres fonctionnalités.





In [49]:
class Joueur (User):
    gagnant = False

In [50]:
mathilde = Joueur(25,"Mathilde")
print(mathilde.ancienneté)
print(mathilde.user_nom)
print(mathilde.gagnant)

0
Mathilde
False


####  La surcharge des méthodes de classe
“Surcharger” une méthode signifie la redéfinir d’une façon différente. 

 En Python les classes filles ou sous-classes peuvent  :
         -  surcharger les méthodes héritées 
         -  définir des variables de même nom que celles de leur classe parent.
         
 

#### Les tests d’héritage Python
comment l’objet fait pour déterminer si il doit utiliser les variables ou méthodes de sa classe ou de la classe mère dont sa classe hérite ?

Python va “remonter” le long de la chaine d’héritage des classes jusqu’à trouver l’information demandée. Si. Elle n’est jamais trouvée, il renverra une erreur.

Il  fournit également deux fonctions pour permettre de tester le type d’une instance et l’héritage d’une classe: 

    - La fonction isinstance() : permet de savoir si un objet appartient à une certaine classe ou pas
    - La fonction issubclass() : permet de savoir si une classe hérite bien d’une autre classe ou pas. 

In [51]:
isinstance(pierre,User) 

True

In [52]:
isinstance(pierre,Joueur)

False

In [53]:
isinstance(mathilde,User) 

True

In [54]:
isinstance(mathilde,Joueur) 

True

In [55]:
issubclass(Joueur, User)

True

In [56]:
issubclass(User, int)

False

#### Le polymorphisme en Python orienté objet
En POO, le polymorphisme est un concept qui fait référence à la capacité d’une variable, d’une fonction ou d’un objet à prendre plusieurs formes, c’est-à-dire à sa capacité de posséder plusieurs définitions différentes.

Un exemple typique de polymorphisme : plusieurs sous-classes héritent d’une méthode d’une classe de base qu’ils implémentent de manière différente.

#### Héritage multiple

On parle d’héritage multiple lorsqu’une sous-classe peut hériter de plusieurs classes mères différentes.

### Gérer la visibilité des membres de classe en Python orienté objet
on peut définir des “niveaux de visibilité” ou “niveaux d’accès” pour les membres des classes (c’est-à-dire pour les variables et les fonctions).

En POO, on distingue généralement trois niveaux de visibilité différents :

Les membres privés auxquels on ne peut accéder que depuis l’intérieur de lac classe ;
Les membres protégés auxquels on ne peut accéder que depuis l’intérieur de la classe ou depuis une classe fille ;
Les membres publics auxquels on peut accéder depuis n’importe quelle instance (ou objet) de la classe ou d’une classe fille.

Ces niveaux de visibilité permettent de “protéger” certains membres de classes qui ne devraient pas être modifiés dans n’importe quelle situation ou depuis n’importe quel endroit.

#### Les niveaux de visibilité des membres de classe en Python par

Par défaut, tous les membres de classe sont publics en Python.

En revanche, certaines conventions ont été mises en place par la communauté Python.

par défaut, tous les membres de classe sont publics en Python.

Attention ici : ce ne sont que des conventions qui n’ont aucun équivalent réel en Python mais tous les membres seront toujours publics en Python


Ces conventions sont les suivantes :

Les noms des membres qu’on souhaite définir comme “privés” avec deux underscores comme ceci :

     __nom-du-membre 
 
Les noms des membres qu’on souhaite définir comme “protégés” avec un underscore comme ceci :

    _nom-du-membre.


Python possède un mécanisme appelé “name mangling” qui fait que tout membre de classe commençant par deux underscores, c’est-à-dire de la forme __nom-du-membre sera remplacé textuellement lors de l’interprétation par _nom-de-classe__nom-du-membre.



In [57]:
class C :
    Public = "variable public"
    _proteted = "variable protégée"
    __Private = "variable privée"
    

In [59]:
objet = Visibilité()
objet.Public

'variable public'

In [61]:
objet._proteted

'variable protégée'

In [62]:
objet.__Private

AttributeError: 'Visibilité' object has no attribute '__Private'

In [63]:
objet._Visibilité__Private

'variable privée'

In [65]:
import numpy as np

class Gamer():

    
    """
    attributs : identification, couleur, nom ou numéro 1 et -1
    methode : faire un choix de colonne

    
    
    joueur_humain(joueur)
    faire un choix de colonne(input)

    joueur_bot(joueur)
    faire un choix de colonne, 2 choix : random ou IA
    """

    def __init__(self, numero, couleur):
        self.numero = numero
        self.couleur = couleur
        #self.choicePlay = choicePlay
        # self.choice = choice


    

    def choicePlay(self):
           
            choice = int(input('Choose your game: \n 1: Player1 Vs Player2 \n 2: Player1 VS Bot \n 3: Bot VS Bot \n'))
            #if self.choice == 1:
            return choice

class HumanGamer(Gamer):

    def input_humain(self):
        print(f" gamer {self.numero :}")
        choice = int(input('Select a number between 0 and 6: '))
        return choice 

class CPUGamer(Gamer):
    
    def input_CPU(self):
        choice = np.random.randint(0, 7) # random player choice
        return choice 







class Board():
    """
    objets : joueurs,  interface d'affichage 
    attribut : plateau, type de joueur
    methode : vérification ligne, colonne, diagonale ; player_input ; global_player(42 coups)

    Principe de gravité (les colonnes se remplissent)


    is_board_full
    is_col_full

    """

    def __init__(self):
        self.nblines_int = 6
        self.nbcolumns_int = 7
        self.board = np.zeros((self.nblines_int, self.nbcolumns_int), dtype=int)

    def displayBoard(self):
        """
        DOCSTRING: Display the board
        """
        board = self.board
        return print(board, "\n")

    def isColFull(self, column:int):
        if 0 not in self.board[:,column]:
            return True
        else:
            return False

    def colChoice(self, player:int, choice:int):
        """
        DOCSTRING: Inserting a coin into a col
        """
    
        if self.isBoardFull():
            return -2
        elif self.isColFull(choice):
            print(f'Column {choice} full')
            return -1
        else:
            column = self.board[:,choice]
            for i in range(0, self.nblines_int)[::-1]:
                if column[i] == 0:
                    column[i] = player
                    break
            return i


    def isBoardFull(self):
        """
        DOCSTRING: 
        """
        return 0 not in self.board[0]



    def a_toi_de_jouer(self, player, choice):
        """
        DOCSTRING: 
        """
      
        line = self.colChoice(player, choice) # Shall we play ?
        if line < 0:
            return line
        
        # Connect4 test on col
        column = self.board[:,choice]
        if np.all(column[line:line+4] == player) and len(column[line:line+4]) == 4:
            return self.board, 1, True
    
        # Connect4 test on line
        window = [player] * 4
        test = np.convolve(self.board[line, max(0, choice-3):choice+4], window)
        if player*4 in test:
            return self.board, 1, True #2
        
        # Connect4 test on diag
        board_padded = np.pad(self.board, (3, 3))
        #m8 = self.board[max(0, line-4):line+4, max(0, choice-4):choice+4]
        m8 = board_padded[line-3+3:line+4+3, choice-3+3:choice+4+3]
    
        d1 = np.diag(m8)
        d2 = np.diag(m8[::-1])
      
      #
        test = np.convolve(d1, window)
        if player*4 in test:
            return self.board, 1, True #3
        
        #
        test = np.convolve(d2, window)
        if player*4 in test:
            return self.board, 1, True
    


class Interface():
    """ terminal et graphique """
    pass




#if __name__ == "__main__":
    B = Board()
    B.displayBoard()
    player = 1
    G = Gamer(player, 'rouge')
    gamechoice = G.choicePlay()
    for i in range(2) :
       
        if gamechoice == 1 or gamechoice == 2:
            # the first gamer is only humain
            G1 = HumanGamer(player, 'jaune')
            choice1 = G1.input_humain()
           
           
        if gamechoice == 3 :
           # the first and the seconde gamers are CPU
            G1 = CPUGamer(player,'jaune')
            choice1 = G1.input_CPU()
            
        
        B.colChoice(1,choice1)
        B.displayBoard()
        B.a_toi_de_jouer(player, choice1)
       
       ######### move to the second player
        player += 1
        if gamechoice == 1 :
            # the second player are humain gamer
            G2  = HumanGamer(player, 'rouge')
            choice2 = G2.input_humain()
        if gamechoice == 2 or gamechoice ==3 :
            #the second gamer is a CPU gamer
            G2  = CPUGamer(player, 'rouge')
            choice2= G2.input_CPU()
        B.colChoice(player,choice2)
        B.displayBoard()
        B.a_toi_de_jouer(player, choice2)
        player -=1


[[0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]] 

Choose your game: 
 1: Player1 Vs Player2 
 2: Player1 VS Bot 
 3: Bot VS Bot 
1
 gamer 1
Select a number between 0 and 6: 2
[[0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [0 0 1 0 0 0 0]] 

 gamer 2
Select a number between 0 and 6: 3
[[0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [0 0 1 0 0 0 0]
 [0 0 1 2 0 0 0]] 

 gamer 1
Select a number between 0 and 6: 2
[[0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [0 0 1 0 0 0 0]
 [0 0 1 2 0 0 0]
 [0 0 1 2 0 0 0]] 

 gamer 2
Select a number between 0 and 6: 3
[[0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [0 0 1 0 0 0 0]
 [0 0 1 2 0 0 0]
 [0 0 1 2 0 0 0]
 [0 0 1 2 0 0 0]] 

